"""Every numeric limit dspy-wasm enforces, in one table.

``dspy_capabilities`` (guest-side request bounds), ``host`` (tool bounds and the
per-call meter defaults), ``consumer/contract.json`` and the README's limits
table are all derived from LIMITS; tests fail if any of them drifts.
Regenerate the derived files with ``python limits.py --write``.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parent


class Limit(NamedTuple):
    value: int | float
    enforced_by: str  # "component": refused before any work; "host": refused or aborted by the host
    meaning: str


LIMITS: dict[str, Limit] = {
    "max_repeat": Limit(10_000, "component", "iterations of one pipeline `repeat`"),
    "max_total_steps": Limit(
        100_000, "component", "steps one pipeline call executes across every nesting level"
    ),
    "max_fanout": Limit(
        100,
        "component",
        "samples `n`/`m` (majority, best-of-n, refine, multi-chain) and retrieval `k`",
    ),
    "max_iters": Limit(
        1_000,
        "component",
        "`max_iters`/`max_llm_calls` of react, program-of-thought, code-act, rlm",
    ),
    "max_interpreter_events": Limit(
        1_000_000,
        "component",
        "trace events (calls, lines, returns) one interpreted-code execution may run",
    ),
    "max_int_bits": Limit(4_096, "host", "bit length of a `calculator` integer result"),
    "max_embed_dimensions": Limit(4_096, "host", "`dimensions` of one `embed` call"),
    "max_embed_texts": Limit(10_000, "host", "texts in one `embed` call"),
    "max_embed_values": Limit(1_048_576, "host", "`texts x dimensions` in one `embed` call"),
    "deadline_s": Limit(600.0, "host", "wall-clock seconds per guest call (`--deadline`)"),
    "max_lm_calls": Limit(20_000, "host", "LM calls per guest call (`--max-lm-calls`)"),
    "max_tool_calls": Limit(100_000, "host", "tool calls per guest call (`--max-tool-calls`)"),
    "max_reply_bytes": Limit(
        268_435_456,
        "host",
        "bytes the host returns to the guest per guest call (`--max-reply-bytes`)",
    ),
}


def value(name: str) -> int | float:
    return LIMITS[name].value


# ------------------------------------------------------------- derived files

README_BEGIN = "<!-- limits:begin (generated by `python limits.py --write`) -->"
README_END = "<!-- limits:end -->"


def readme_block() -> str:
    rows = [
        "| limit | value | enforced by | meaning |",
        "|-------|-------|-------------|---------|",
    ]
    for name, limit in LIMITS.items():
        rows.append(f"| `{name}` | {limit.value:,} | {limit.enforced_by} | {limit.meaning} |")
    return "\n".join([README_BEGIN, *rows, README_END])


def contract_limits() -> dict[str, int | float]:
    return {name: limit.value for name, limit in LIMITS.items()}


def _rewrite_readme(text: str) -> str:
    pattern = re.compile(re.escape(README_BEGIN) + r".*?" + re.escape(README_END), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit("README.md has no limits block")
    return pattern.sub(lambda _: readme_block(), text)


def write() -> None:
    readme = ROOT / "README.md"
    readme.write_text(_rewrite_readme(readme.read_text()))
    contract = ROOT / "consumer" / "contract.json"
    data = json.loads(contract.read_text())
    data["limits"] = contract_limits()
    contract.write_text(json.dumps(data, indent=2) + "\n")


if __name__ == "__main__":
    if sys.argv[1:] == ["--write"]:
        write()
    else:
        raise SystemExit("usage: python limits.py --write")
